apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "waiconv.fullname" . }}
  labels:
    {{- include "waiconv.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "waiconv.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: app
  template:
    metadata:
      labels:
        {{- include "waiconv.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: app
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - name: http
          containerPort: 8000
          protocol: TCP
        env:
        - name: REDIS_HOST
          value: {{ default (printf "%s-redis" (include "waiconv.fullname" .)) .Values.config.redis.host | quote }}
        - name: REDIS_PORT
          value: {{ .Values.config.redis.port | quote }}
        - name: REDIS_DB
          value: {{ .Values.config.redis.db | quote }}
        - name: REDIS_MESSAGES_KEY
          value: {{ .Values.config.redis.key | quote }}
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: {{ .Values.config.kafka.bootstrapServers | quote }}
        - name: KAFKA_SASL_USERNAME
          value: {{ .Values.config.kafka.saslUsername | quote }}
        - name: KAFKA_SASL_PASSWORD
          value: {{ .Values.config.kafka.saslPassword | quote }}
        - name: KAFKA_TOPIC
          value: {{ .Values.config.kafka.topic | quote }}
        - name: KAFKA_GROUP_ID
          value: {{ .Values.config.kafka.groupId | quote }}
        - name: KAFKA_SASL_ENABLED
          value: {{ ternary "true" "false" .Values.config.kafka.saslEnabled | quote }}
        - name: KAFKA_SECURITY_PROTOCOL
          value: {{ .Values.config.kafka.securityProtocol | quote }}
        - name: KAFKA_SASL_MECHANISM
          value: {{ .Values.config.kafka.saslMechanism | quote }}
        - name: POSTGRES_HOST
          value: {{ default (printf "%s-postgres" (include "waiconv.fullname" .)) .Values.config.postgres.host | quote }}
        - name: POSTGRES_PORT
          value: "{{ .Values.postgres.service.port }}"
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: {{ default (printf "%s-postgres-secret" (include "waiconv.fullname" .)) .Values.postgres.existingSecret | quote }}
              key: database
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: {{ default (printf "%s-postgres-secret" (include "waiconv.fullname" .)) .Values.postgres.existingSecret | quote }}
              key: username
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ default (printf "%s-postgres-secret" (include "waiconv.fullname" .)) .Values.postgres.existingSecret | quote }}
              key: password
        - name: MAX_MESSAGES
          value: {{ .Values.config.maxMessages | quote }}
        livenessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /api/messages
            port: http
          initialDelaySeconds: 5
          periodSeconds: 5
        {{- with .Values.resources }}
        resources:
          {{- toYaml . | nindent 10 }}
        {{- end }}
